import type { Product } from "@/types/product"

// ─── CATEGORIES — expanded Nigerian market ────────────────────
export const CATEGORIES = [
  { value: "all",         label: "All Products" },
  { value: "electronics", label: "Electronics" },
  { value: "fashion",     label: "Fashion" },
  { value: "food",        label: "Food & Drinks" },
  { value: "beauty",      label: "Beauty & Skincare" },
  { value: "home",        label: "Home & Living" },
  { value: "health",      label: "Health & Wellness" },
  { value: "sports",      label: "Sports & Fitness" },
  { value: "automotive",  label: "Automotive" },
  { value: "books",       label: "Books & Stationery" },
  { value: "audio",       label: "Audio & Music" },
  { value: "babies",      label: "Baby & Kids" },
  { value: "agriculture", label: "Agriculture" },
  { value: "arts",        label: "Art & Crafts" },
  { value: "phones",      label: "Phones & Tablets" },
  { value: "computers",   label: "Computers & Accessories" },
  { value: "furniture",   label: "Furniture" },
  { value: "jewelry",     label: "Jewelry & Accessories" },
  { value: "travel",      label: "Travel & Luggage" },
  { value: "other",       label: "Other" },
]

export const SORT_OPTIONS = [
  { value: "newest",     label: "Newest First" },
  { value: "popular",    label: "Most Popular" },
  { value: "rating",     label: "Top Rated" },
  { value: "price-asc",  label: "Price: Low to High" },
  { value: "price-desc", label: "Price: High to Low" },
] as const

export const PRICE_RANGES = [
  { label: "Under ₦5,000",       min: 0,      max: 5000 },
  { label: "₦5,000 – ₦20,000",   min: 5000,   max: 20000 },
  { label: "₦20,000 – ₦50,000",  min: 20000,  max: 50000 },
  { label: "₦50,000 – ₦100,000", min: 50000,  max: 100000 },
  { label: "Above ₦100,000",      min: 100000, max: 999999 },
]

// ─── MOCK PRODUCTS ────────────────────────────────────────────
export const MOCK_PRODUCTS: Product[] = [
  // ── FASHION ──
  {
    id: "1",
    slug: "ankara-fabric-6-yards",
    name: "Premium Ankara Fabric (6 Yards)",
    description: "Vibrant 100% cotton Ankara fabric. Perfect for traditional attire, aso-ebi, and fashion designs. Available in bold, colourful patterns.",
    price: 8500, originalPrice: 12000,
    images: ["/products/Ankara-dress.jpg"],
    category: "fashion",
    vendor: { id: "v1", name: "Lagos Fabrics Hub", rating: 4.8, location: "Lagos Island", isVerified: true },
    rating: 4.8, reviewCount: 214, stock: 45,
    tags: ["ankara", "fabric", "traditional", "aso-ebi"],
    isFeatured: true,
  },
  {
    id: "2",
    slug: "senator-agbada-set",
    name: "Premium Senator Agbada 3-Piece Set",
    description: "Beautifully embroidered Agbada set. Includes gown, sokoto, and cap. Perfect for owambe, weddings, and special occasions.",
    price: 28000, originalPrice: 35000,
    images: ["/products/Senator-Agbada.jpg"],
    category: "fashion",
    vendor: { id: "v10", name: "Royal Attire Lagos", rating: 4.6, location: "Surulere, Lagos", isVerified: true },
    rating: 4.6, reviewCount: 156, stock: 20,
    tags: ["agbada", "senator", "native", "owambe"],
  },
  {
    id: "3",
    slug: "leather-palm-slippers",
    name: "Handcrafted Leather Palm Slippers",
    description: "Premium genuine leather palm slippers from Aba craftsmen. Comfortable and stylish for everyday wear. Sizes 38–46.",
    price: 8500, originalPrice: 12000,
    images: ["/products/LeatherPalm-Slippers.jpg"],
    category: "fashion",
    vendor: { id: "v5", name: "Aba Leather Works", rating: 4.9, location: "Aba, Abia State", isVerified: true },
    rating: 4.9, reviewCount: 445, stock: 60,
    tags: ["slippers", "leather", "aba", "footwear"],
    isFeatured: true,
  },
  {
    id: "4",
    slug: "adire-tie-dye-fabric",
    name: "Adire Tie-Dye Fabric (5 Yards)",
    description: "Authentic hand-dyed Adire fabric from Abeokuta. Each piece is unique. Perfect for dresses, skirts, and traditional wear.",
    price: 6500,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"],
    category: "fashion",
    vendor: { id: "v13", name: "Abeokuta Textiles", rating: 4.7, location: "Abeokuta, Ogun", isVerified: true },
    rating: 4.7, reviewCount: 89, stock: 35,
    tags: ["adire", "tie-dye", "abeokuta", "fabric"],
    isNew: true,
  },

  // ── ELECTRONICS & PHONES ──
  {
    id: "5",
    slug: "tecno-camon-30-pro",
    name: "Tecno Camon 30 Pro 5G",
    description: "6.78 AMOLED display, 50MP triple camera, 5000mAh battery with 33W fast charging. The best mid-range smartphone for Nigerian users.",
    price: 189000, originalPrice: 210000,
    images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=600&q=80"],
    category: "phones",
    vendor: { id: "v3", name: "PhoneWorld NG", rating: 4.7, location: "Computer Village, Lagos", isVerified: true },
    rating: 4.7, reviewCount: 312, stock: 28,
    tags: ["phone", "smartphone", "tecno", "5g"],
    isFeatured: true, isNew: true,
  },
  {
    id: "6",
    slug: "infinix-hot-40",
    name: "Infinix Hot 40 Pro",
    description: "6.78 HD+ display, 108MP camera, 5000mAh battery with 45W fast charging. Great value Nigerian smartphone.",
    price: 145000,
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=600&q=80"],
    category: "phones",
    vendor: { id: "v3", name: "PhoneWorld NG", rating: 4.7, location: "Computer Village, Lagos", isVerified: true },
    rating: 4.5, reviewCount: 198, stock: 40,
    tags: ["infinix", "phone", "smartphone"],
    isNew: true,
  },
  {
    id: "7",
    slug: "solar-panel-200w",
    name: "200W Monocrystalline Solar Panel",
    description: "High-efficiency 200W solar panel. Perfect for home solar installations, borehole pumping, and off-grid power systems.",
    price: 68000,
    images: ["https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&q=80"],
    category: "electronics",
    vendor: { id: "v7", name: "GreenEnergy NG", rating: 4.6, location: "Ibadan", isVerified: true },
    rating: 4.6, reviewCount: 134, stock: 35,
    tags: ["solar", "energy", "renewable"],
    isNew: true,
  },
  {
    id: "8",
    slug: "innoson-generator-3-5kva",
    name: "Innoson Generator 3.5KVA",
    description: "Fuel-efficient 3.5KVA generator. Ideal for home and small business. Electric start, low noise, AVR stabilizer included.",
    price: 145000, originalPrice: 165000,
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"],
    category: "electronics",
    vendor: { id: "v4", name: "Power Solutions NG", rating: 4.5, location: "Onitsha", isVerified: true },
    rating: 4.5, reviewCount: 67, stock: 15,
    tags: ["generator", "power", "electricity"],
  },

  // ── FOOD & DRINKS ──
  {
    id: "9",
    slug: "nigeria-food-pack",
    name: "Nigerian Food Essentials Pack",
    description: "Premium selection of Nigerian food staples including rice, beans, palm oil, crayfish, and dried fish.",
    price: 32000,
    images: ["/products/Nigeria-food.jpg"],
    category: "food",
    vendor: { id: "v2", name: "Abuja Grocery Store", rating: 4.6, location: "Abuja", isVerified: true },
    rating: 4.6, reviewCount: 98, stock: 200,
    tags: ["food", "rice", "staple", "groceries"],
    isFeatured: true,
  },
  {
    id: "10",
    slug: "zobo-drink-pack",
    name: "Natural Zobo Drink (12 Bottles)",
    description: "Freshly brewed hibiscus zobo drink. No artificial colouring or preservatives. Chilled and refreshing Nigerian classic.",
    price: 4800, originalPrice: 6000,
    images: ["https://images.unsplash.com/photo-1546171753-97d7676e4602?w=600&q=80"],
    category: "food",
    vendor: { id: "v6", name: "Natural Drinks NG", rating: 4.4, location: "Port Harcourt", isVerified: false },
    rating: 4.4, reviewCount: 88, stock: 120,
    tags: ["zobo", "drink", "hibiscus", "natural"],
  },
  {
    id: "11",
    slug: "ofada-rice-5kg",
    name: "Premium Ofada Rice 5kg",
    description: "Authentic Nigerian ofada rice from Ogun State. Stone-free, nutritious, and perfect with ofada stew.",
    price: 8500,
    images: ["https://images.unsplash.com/photo-1586201375761-83865001e31c?w=600&q=80"],
    category: "food",
    vendor: { id: "v14", name: "Farm Direct NG", rating: 4.8, location: "Ogun State", isVerified: true },
    rating: 4.8, reviewCount: 203, stock: 150,
    tags: ["ofada", "rice", "local", "ogun"],
    isFeatured: true,
  },

  // ── BEAUTY ──
  {
    id: "12",
    slug: "shea-butter-pure-500g",
    name: "Pure Unrefined Shea Butter 500g",
    description: "100% natural unrefined shea butter from Northern Nigeria. Great for skin, hair growth, and stretch marks.",
    price: 3500,
    images: ["https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=600&q=80"],
    category: "beauty",
    vendor: { id: "v12", name: "NaturalGlow NG", rating: 4.9, location: "Kaduna", isVerified: true },
    rating: 4.9, reviewCount: 521, stock: 300,
    tags: ["shea butter", "natural", "skincare", "hair"],
    isFeatured: true,
  },
  {
    id: "13",
    slug: "black-soap-natural",
    name: "Authentic African Black Soap 500g",
    description: "Traditional African black soap handmade in Ghana and Nigeria. Deep cleanser for face and body. Great for acne and eczema.",
    price: 2800,
    images: ["https://images.unsplash.com/photo-1556228453-efd6c1ff04f6?w=600&q=80"],
    category: "beauty",
    vendor: { id: "v12", name: "NaturalGlow NG", rating: 4.9, location: "Kaduna", isVerified: true },
    rating: 4.7, reviewCount: 287, stock: 200,
    tags: ["black soap", "natural", "skincare", "african"],
  },
  {
    id: "14",
    slug: "coconut-oil-raw",
    name: "Cold-Pressed Coconut Oil 1 Litre",
    description: "100% pure cold-pressed coconut oil. Multi-purpose — cooking, hair moisturising, skin care. Sourced from Nigerian farms.",
    price: 4200,
    images: ["https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600&q=80"],
    category: "beauty",
    vendor: { id: "v15", name: "Pure Naturals NG", rating: 4.6, location: "Enugu", isVerified: true },
    rating: 4.6, reviewCount: 142, stock: 180,
    tags: ["coconut oil", "natural", "hair", "cooking"],
  },

  // ── AUDIO & TECH ──
  {
    id: "15",
    slug: "jbl-flip-6-speaker",
    name: "JBL Flip 6 Bluetooth Speaker",
    description: "Portable waterproof Bluetooth speaker with bold JBL Pro Sound, 12 hours playtime and powerful bass.",
    price: 52000, originalPrice: 65000,
    images: ["https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&q=80"],
    category: "audio",
    vendor: { id: "v9", name: "TechGadgets NG", rating: 4.8, location: "Victoria Island, Lagos", isVerified: true },
    rating: 4.8, reviewCount: 267, stock: 42,
    tags: ["speaker", "jbl", "bluetooth", "music"],
    isFeatured: true,
  },
  {
    id: "16",
    slug: "wireless-earbuds-pro",
    name: "Wireless Earbuds Pro — Active Noise Cancelling",
    description: "True wireless earbuds with ANC, 30hr total battery life, IPX5 waterproof. Premium sound for Nigerian commuters.",
    price: 35000, originalPrice: 45000,
    images: ["https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&q=80"],
    category: "audio",
    vendor: { id: "v9", name: "TechGadgets NG", rating: 4.8, location: "Victoria Island, Lagos", isVerified: true },
    rating: 4.6, reviewCount: 189, stock: 55,
    tags: ["earbuds", "wireless", "anc", "music"],
    isNew: true,
  },

  // ── BOOKS ──
  {
    id: "17",
    slug: "nigerian-cookbook",
    name: "The Complete Nigerian Cookbook",
    description: "200+ authentic Nigerian recipes. From jollof rice to egusi soup, suya, moin moin, puff puff and more.",
    price: 5200,
    images: ["https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=600&q=80"],
    category: "books",
    vendor: { id: "v8", name: "Lagos Book Store", rating: 4.7, location: "Lagos", isVerified: true },
    rating: 4.7, reviewCount: 203, stock: 80,
    tags: ["book", "cooking", "nigerian", "recipes"],
  },
  {
    id: "18",
    slug: "things-fall-apart",
    name: "Things Fall Apart — Chinua Achebe",
    description: "The timeless classic by Chinua Achebe. Essential Nigerian literature for every bookshelf. Paperback edition.",
    price: 2500,
    images: ["https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80"],
    category: "books",
    vendor: { id: "v8", name: "Lagos Book Store", rating: 4.7, location: "Lagos", isVerified: true },
    rating: 4.9, reviewCount: 412, stock: 120,
    tags: ["book", "chinua achebe", "classic", "literature", "nigeria"],
    isFeatured: true,
  },

  // ── HEALTH ──
  {
    id: "19",
    slug: "moringa-powder-200g",
    name: "Organic Moringa Leaf Powder 200g",
    description: "100% pure organic moringa powder. Rich in vitamins and minerals. Boosts immunity and energy naturally.",
    price: 3800,
    images: ["https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600&q=80"],
    category: "health",
    vendor: { id: "v16", name: "HealthPlus NG", rating: 4.7, location: "Abuja", isVerified: true },
    rating: 4.7, reviewCount: 156, stock: 200,
    tags: ["moringa", "health", "organic", "natural"],
    isNew: true,
  },

  // ── AUTOMOTIVE ──
  {
    id: "20",
    slug: "bajaj-boxer-motorcycle",
    name: "Bajaj Boxer 150 Motorcycle",
    description: "Reliable 150cc motorcycle for commercial and personal use. Fuel-efficient, easy to maintain.",
    price: 490000,
    images: ["https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=600&q=80"],
    category: "automotive",
    vendor: { id: "v11", name: "Bajaj NG Dealers", rating: 4.5, location: "Kano", isVerified: true },
    rating: 4.5, reviewCount: 89, stock: 8,
    tags: ["bajaj", "motorcycle", "bike", "commercial"],
  },

  // ── AGRICULTURE ──
  {
    id: "21",
    slug: "farm-fresh-palm-oil",
    name: "Farm Fresh Red Palm Oil 5 Litres",
    description: "Pure unrefined red palm oil from Benue State farms. Rich colour and flavour. Ideal for soups and stews.",
    price: 12000,
    images: ["https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80"],
    category: "agriculture",
    vendor: { id: "v17", name: "Benue Farm Produce", rating: 4.8, location: "Benue State", isVerified: true },
    rating: 4.8, reviewCount: 234, stock: 85,
    tags: ["palm oil", "farm", "natural", "cooking"],
    isFeatured: true,
  },

  // ── HOME ──
  {
    id: "22",
    slug: "ankara-cushion-covers",
    name: "Ankara Print Cushion Covers (Set of 4)",
    description: "Vibrant Ankara print cushion covers. Add a pop of African colour to your living room. Set of 4 in assorted patterns.",
    price: 6500,
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80"],
    category: "home",
    vendor: { id: "v18", name: "Naija Home Decor", rating: 4.5, location: "Lagos", isVerified: true },
    rating: 4.5, reviewCount: 78, stock: 95,
    tags: ["ankara", "home decor", "cushion", "living room"],
    isNew: true,
  },

  // ── BABIES & KIDS ──
  {
    id: "23",
    slug: "childrens-yoruba-book",
    name: "My First Yoruba Words — Children's Book",
    description: "Beautifully illustrated bilingual book teaching children basic Yoruba words. Ages 2–8. Perfect for Nigerian families abroad.",
    price: 3200,
    images: ["https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&q=80"],
    category: "babies",
    vendor: { id: "v8", name: "Lagos Book Store", rating: 4.7, location: "Lagos", isVerified: true },
    rating: 4.9, reviewCount: 112, stock: 60,
    tags: ["children", "book", "yoruba", "education", "bilingual"],
    isNew: true,
  },

  // ── JEWELRY ──
  {
    id: "24",
    slug: "beaded-waist-beads",
    name: "Traditional Waist Beads Set",
    description: "Handcrafted African waist beads in vibrant colours. Symbol of femininity and beauty. Adjustable sizing.",
    price: 2500,
    images: ["https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80"],
    category: "jewelry",
    vendor: { id: "v19", name: "Naija Beads", rating: 4.6, location: "Lagos", isVerified: false },
    rating: 4.6, reviewCount: 198, stock: 150,
    tags: ["waist beads", "jewelry", "african", "traditional"],
    isFeatured: true,
  },
]

// ─── HELPERS ──────────────────────────────────────────────────
export function formatNaira(amount: number): string {
  return `\u20a6${amount.toLocaleString("en-NG")}`
}

export function getDiscountPercent(price: number, originalPrice: number): number {
  return Math.round(((originalPrice - price) / originalPrice) * 100)
}
